### ISSUE TITLE
Right-click menu items not working

### ISSUE THREAD

**Issue by rtheodoro** [pop-os/desktop-icons-ng#3] opened 2020-11-25 17:29 UTC
Every time I try to use another application to open a file on my Desktop, nothing happens.

To reproduce:
Place a file in Desktop (.csv, for example). By default the .csv is opened with  Text Editor. If I click with the mouse right button, and select "open with another application", nothing happens.
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
```
GNOME Shell 3.38.1
```
```
pop-shell:
  Instalado: 1.0.0~1605809546~20.10~1a8b13f
  Candidato: 1.0.0~1605809546~20.10~1a8b13f
  Tabela de versão:
 *** 1.0.0~1605809546~20.10~1a8b13f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```
```
Multi Monitors Add On and Sound Input and Output Device Chooser
```

**Comment by jacobgkau** [comment] 2020-11-25 22:25
I'm transferring this issue because desktop icons are handled by their own extension, not the Pop Shell extension. Pop Shell handles window tiling.

I am not able to reproduce this issue (if I place a .csv on my desktop, it opens with LibreOffice Calc by default, but I can also click "Open With Other Application" and open it with Gedit, for example.)

**Comment by rtheodoro** [comment] 2020-11-26 01:49
I just realized that "Configuration" (Configurações, in Portuguese) doesn't open too. 

Where can I report?

**Comment by jacobgkau** [comment] 2020-11-30 16:04
That's interesting. The English version says "Settings", not "Configuration". After changing the system's language to Portuguese (Brazil) and restarting the session, I'm still seeing the labels in English for some reason, even though there is a Portuguese (BR) translation file present: https://github.com/pop-os/desktop-icons-ng/blob/master/po/pt_BR.po 

After installing the upstream version locally from extensions.gnome.org, the translation works. I see the "Configurações" item in the right-click menu, and that works, along with "Abrir com outro aplicativo" ("Open With Other Application").

If you create a new user account (Settings -> Users) then log out of your normal account and into the new account, do those menu items work? Please check before and after changing the language in the new account, if you can.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by rtheodoro** [comment] 2020-11-30 17:26
Thanks!

This problem was solved here, in another problem: https://github.com/pop-os/gnome-control-center/issues/130

I just put `sudo ldconfig`, updated everything and rebooted my system.

**Closed as completed** 2020-12-01 18:11 UTC
